<?php

namespace Wiki\AdminBundle\Entity;

/**
 * projetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class projetRepository extends \Doctrine\ORM\EntityRepository
{
}
