<?php

namespace Wiki\WikiMaireBundle\Entity;

/**
 * ProjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetRepository extends \Doctrine\ORM\EntityRepository
{

    public function RechercheProjet($tags)
    {
        $queryBuilder = $this->_em->createQueryBuilder()
            ->select('p')
            ->from($this->_entityName, 'p')// Dans un repository, $this->_entityName est le namespace de l'entité gérée
            ->Where('p.tags LIKE :str')
            ->setParameter('str', '%'.$tags.'%');
        $query = $queryBuilder->getQuery();
        return $query->getResult();
    }
}
