<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\UserBundle\Entity;

use Sonata\UserBundle\Entity\BaseUser as BaseUser;


/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class User extends BaseUser
{



    public $fil;

    protected function getUploadDir()
    {
        return 'photos';
    }

    protected function getUploadRootDir()
    {
        return __DIR__.'/../../../../../web/'.$this->getUploadDir();
    }

    public function getWebPath()
    {
        return null === $this->photoprofil ? null : $this->getUploadDir().'/'.$this->photoprofil;
    }

    public function getAbsolutePath()
    {
        return null === $this->photoprofil ? null : $this->getUploadRootDir().'/'.$this->photoprofil;
    }


    public function preUpload()
    {
        if (null !== $this->fil) {
            // do whatever you want to generate a unique name
            $this->photoprofil= uniqid() . '.' . $this->fil->guessExtension();
        }
    }


    public function upload()
    {
        if (null === $this->fil) {
            return;
        }

        // if there is an error when moving the file, an exception will
        // be automatically thrown by move(). This will properly prevent
        // the entity from being persisted to the database on error
        $this->fil->move($this->getUploadRootDir(), $this->photoprofil);

        unset($this->fil);
    }


    public function removeUpload()
    {
        if ($fil = $this->getAbsolutePath()) {
            unlink($fil);
        }
    }



    // GENERATED CODE

    /**
     * @var integer $id
     */
    protected $id;

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }
    /**
     * @var \Wiki\WikiMaireBundle\Entity\Commune
     */
    private $commune;


    /**
     * Set commune
     *
     * @param \Wiki\WikiMaireBundle\Entity\Commune $commune
     *
     * @return User
     */
    public function setCommune(\Wiki\WikiMaireBundle\Entity\Commune $commune = null)
    {
        $this->commune = $commune;

        return $this;
    }

    /**
     * Get commune
     *
     * @return \Wiki\WikiMaireBundle\Entity\Commune
     */
    public function getCommune()
    {
        return $this->commune;
    }


    /**
     * @var string
     */
    private $adressemairie;

    /**
     * @var string
     */
    private $bassindepopulation;


    /**
     * Set adressemairie
     *
     * @param string $adressemairie
     *
     * @return User
     */
    public function setAdressemairie($adressemairie)
    {
        $this->adressemairie = $adressemairie;

        return $this;
    }

    /**
     * Get adressemairie
     *
     * @return string
     */
    public function getAdressemairie()
    {
        return $this->adressemairie;
    }

    /**
     * Set bassindepopulation
     *
     * @param string $bassindepopulation
     *
     * @return User
     */
    public function setBassindepopulation($bassindepopulation)
    {
        $this->bassindepopulation = $bassindepopulation;

        return $this;
    }

    /**
     * Get bassindepopulation
     *
     * @return string
     */
    public function getBassindepopulation()
    {
        return $this->bassindepopulation;
    }

    /**
     * @var string
     */
    private $photoprofil;


    /**
     * Set photoprofil
     *
     * @param string $photoprofil
     *
     * @return User
     */
    public function setPhotoprofil($photoprofil)
    {
        $this->photoprofil = $photoprofil;

        return $this;
    }

    /**
     * Get photoprofil
     *
     * @return string
     */
    public function getPhotoprofil()
    {
        return $this->photoprofil;
    }

}
